config/routes.rb
Rails.application.routes.draw do


  resources :users do
    resources :posts #posts as nested ressource within users
  end

  root 'home#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  validates :poster, :presence => true
  validates :title, :presence => true
  validates :content, :presence => true

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :presence => true
  validates :beschreibung, :presence => true
  validates :eMailAddress, :presence => true


  has_many :posts, :dependent => :destroy



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render("index")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.create(post_params)
    redirect_to user_path(@user)

    #validates :name, :presence => true
    #validates :beschreibung, :presence => true
    #validates :eMailAddress, :presence => true
    #respond_to do |format|
      #if @post.save
        #format.html { redirect_to @post, notice: 'Post was successfully created.' }
       # format.json { render :show, status: :created, location: @post }
      #else
       # format.html { render :new }
      #  format.json { render json: @post.errors, status: :unprocessable_entity }
     # end
    #end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.destroy



    redirect_to user_path(@user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:poster, :title, :content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
      @post = User.find(params[:id])
      @user_all = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        #format sagt, dass bei format.html eine html seite zurückgegeben werden soll und bei format.json eine json datei so kann man die Daten z.B. mit /new.json einfach so abfragen
        format.html { redirect_to @user, notice: 'User was successfully created.' } #man wird zu user#show weitergeleitet
        format.json { render :show, status: :created, location: @user }

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy


    #@test = Post.find(poster: params[:id])
    @test2 = Post.find_by poster: params[:id]
    #@test.destroy
    if @test2.nil?
      puts "hallo"
      else
      @test2.destroy
    end

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :beschreibung, :eMailAddress)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<header class="jumbotron">
  <div>
  <h1>Welcome to my Uebung3-Test Heroku Site</h1>
  <h5>here you can create a user and add a comment to this specific user or other</h5>
  </div>
</header>
<article>
  <section>

  </section>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uebung3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="container">
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%=root_path%>">Uebung3-Test-Project</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=root_path%>">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= users_path %>">Users</a>
      </li>

    </ul>
  </nav>
  <div class="py-3">

    <%= yield %>

  </div>
  </body>
</html>

app/views/pages/index.html.erb
<body class="container">
<nav class="bg-secondary nav-corners">
  <div class="row navbar text-center">

    <div class="col-3 active text-center"><a class="col-3 text-white " href="index.html">Home</a></div>
    <div class="col-3 nav-item active "><a class="col-3  text-white" href="Deckblatt.html">Deckblatt</a></div>
    <div class="col-3 nav-item active "><a class="col-3  text-white" href="Anschreiben.html">Anschreiben</a></div>
    <div class="col-3 nav-item active "><a class="col-3 text-white" href="Lebenslauf.html">Lebenslauf</a></div>


  </div>
</nav>
<header>
  <div class="row" >
    <div class="col-3">
      <p class="container bg-secondary text-white" id="header-box">
        Anschreiben
      </p>
    </div>
  </div>
</header>
<article>
  <address class="my-3">
    <p>
      Max Mustermann <br>
      Musterstraße 23 <br>
      12345 Musterstadt
    </p>
  </address>
  <address class="my-3">
    <p>Musterarbeitgeber GmbH<br>
      Frau Anja Mustermann<br>
      Musterstraße 22<br>
      12345 Musterstadt
    </p>
  </address>
  <section>
    <p class="text-right">
      01.01.2018
    </p>
  </section>
  <div>
    <section>
      <p>
      <h4>Bewerbung als Softwareentwickler</h4> <!-- h macht auch einen Zeilenumbruch am ende-->
      Ihre Stellenanzeige vom 31.12.2017 auf Lebenslauf.net | Referenznummer A-12345
      </p>
    </section>
    <section>
      <p>
      <p>
        Sehr geehrte Frau Mustermann,
      </p>
      <p>
        Ihr Stellenangebot für die Position des Junior-Beraters ist die perfekte Möglichkeit, meine analytische Denkweise und mein breites Wissen aus meinem MBA in der Praxis anzuwenden. (UNTERNEHMESNAME) als führendes Beratungsunternehmen bietet mir die gesuchte Herausforderung um als Berater in einem internationalen Umfeld tätig zu sein an spannenden Projekten weltweit mitzuwirken.
      </p>
      <p>
        Während meiner Ausbildung bei (UNTERNEHMENSNAME) habe ich eigenständig Projekte initiiert und organisiert und meine Ausbilder von meinem Talent als Versicherungsberater überzeugt. Meine Kommunikations- und Organisationsfähigkeit und meine Leidenschaft fürs Kundenmanagement zeigten sich deutlich in meinen Beratungserfolgen und Kundenbewertungen und ließen mich frühzeitig Führungsverantwortung übernehmen.
      </p>
      <p>
        Für weitere Fragen stehe ich gerne zur Verfügung. Auf eine persönliche Vorstellung, in der ich Sie von meinen fachlichen Kenntnissen und Motivation überzeugen kann, freue ich mich.
      </p>
      <p>
        Mit freundlichen Grüßen
      </p>
      <p>
        <br> Max Mustermann
      </p>
      </p>
    </section>
  </div>
  <section class="anlagen">
    <p>
      Anlagen
    </p>
    <ul>
      <li>Lebenslauf</li>
    </ul>
  </section>
</article>
<footer class="page-footer mt-4 container bg-secondary footer-stuff">
  <div class="text-center text-white mt-5">
    Thom, Florian: Web Entwicklung: Bewerbungsmappe 2018
  </div>
</footer>

app/views/posts/_form.html.erb
<%= form_for([@user, @user.posts.build]) do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-1 row">
    <div class="field col-2">
    <%= form.label :poster, "Poster-ID" %>
    </div>
    <div class="col-10">
        <%= form.collection_select :poster, User.all, :id, :id %>



  </div>
  </div>

  <div class="my-1 row">
    <div class="field col-2">
    <%= form.label :title %>
    </div>
      <div class="col-10">
    <%= form.text_field :title %>
  </div>
    </div>

    <div class="my-1 row">
      <div class="field col-2">
    <%= form.label :content %>
      </div>
        <div class="col-10">
    <%= form.text_area :content%>
  </div>
      </div>



  <div class="actions">
    <%= form.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p>
  <b>Poster - ID:</b>
  <%= post.poster %>
</p>
  <b>Title:</b>
  <%= post.title %>
</p>
<p>
  <b>Comment:</b>
  <%= post.content %>
</p>

<p>
  <%= link_to 'Delete Post', [post.user, post],
              :confirm => 'Are you sure?',
              :method => :delete %>
</p>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Poster</th>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.poster %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Poster:</strong>
  <%= @post.poster %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<div class="my-5 row">
  <div class="field col-2">
    <%= form.label :name %>
  </div>
  <div class="col-10">
    <%= form.text_field :name, id: :user_name %>
  </div>
</div>

  <div class="my-5 row">
  <div class="field col-2">
    <%= form.label :Description %>
    </div>
  <div class="col-10">
    <%= form.text_area :beschreibung, id: :user_beschreibung %>
  </div>
  </div>

  <div class="my-5 row">
  <div class="field col-2">
    <%= form.label :eMail %>
  </div><div class="col-10">
    <%= form.text_field :eMailAddress, id: :user_eMailAddress %>
</div>
  </div>

  <div class="actions col-sm-10 px-0">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>


<div class="row py-3">
  <div class="col-2"> User - ID</div>
      <div class="col-2"> Name</div>
  <div class="col-2">Description</div>
  <div class="col-2">Email</div>

</div>

    <% @users.each do |user| %>
      <div class="row py-1">
        <div class="col-2"> <%= user.id %></div>
        <div class="col-2"> <%= user.name %></div>
        <div class="col-2"><%= user.beschreibung %></div>
        <div class="col-2"><%= user.eMailAddress %></div>
        <div class="col-1"> <%= link_to 'View', user %></div>
        <div class="col-1"><%= link_to 'Edit', edit_user_path(user) %></div>
          <div class="col-1"><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></div>
      </div>
    <% end %>

<br>


<%= link_to 'New User', new_user_path, class: "btn btn-primary" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<div class="my-5 container">
<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>User</h1>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.beschreibung %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.eMailAddress %>
</p>
<p>
  <strong>User - ID:</strong>
  <%= @user.id%>
</p>




<div class="pt-5">
<h2>Comments</h2>
<%= render @user.posts%>
</div>
<hr class="my-5">
<h2>Create Comment</h2>

<div class="pt-3">
<%= render "posts/form" %>
  </div>

<div class="my-5">
<%= link_to 'Edit', edit_user_path(@user)%> |
<%= link_to 'Back', users_path %>
</div>